### ISSUE TITLE
Wikipedia的数据集为什么被删除了呀？想下载来着

### ISSUE THREAD

**Issue by neophyte526** [qinchuanhui/UDA-Benchmark#1]
![微信图片_20241217110956](https://github.com/user-attachments/assets/36a4f020-8272-4c8b-9037-f9239894062f)

**Comment by qinchuanhui** [comment]
There's a version issue with the wiki pages. I will fix it in several days.

**Comment by neophyte526** [comment]
Thank you very much❤️



---原始邮件---
发件人: "Yulong ***@***.***&gt;
发送时间: 2024年12月17日(周二) 下午4:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qinchuanhui/UDA-Benchmark] Wikipedia的数据集为什么被删除了呀？想下载来着 (Issue #1)




 
There's a version issue with the wiki pages. I will fix it in several days.

**Comment by qinchuanhui** [comment]
I have updated the dataset on huggingface 😊
